from .dashboard_view import dashboard_view
from .tasks_view import tasks_view
from .incoming_view import incoming_view
from .avs_view import avs_view
from .av_view import av_view
from .av_save import av_save
from .av_create import av_create
from .av_search import av_search
from .avs_upload import avs_upload
from .suppliers_view import suppliers_view
from .supplier_view import supplier_view
from .supplier_save import supplier_save
from .supplier_delete import supplier_delete
from .supplier_create import supplier_create
from .machines_view import machines_view
from .machine_view import machine_view
from .machine_save import machine_save
from .machine_create import machine_create
from .machine_delete import machine_delete
from .drives_view import drives_view
from .drive_view import drive_view
from .drive_save import drive_save
from .drive_create import drive_create
from .drive_delete import drive_delete
from .av_assign import av_assign
from .av_prio import av_prio
from .incoming_procedure_view import incoming_procedure_view
from .incoming_procedure_save import incoming_procedure_save
from .archivist_view import archivist_view
from .archivist_save import archivist_save
from .archivists_view import archivists_view
from .archivist_create import archivist_create
from .archivist_delete import archivist_delete
from .upload_view import upload_view
from .export_csv import export_csv
from .export_xls import export_xls
from .export_machines import export_machines
from .import_machines import import_machines
from .export_drives import export_drives
from .import_drives import import_drives
from .overblik import overblik
from .genberegn_svarfirst import genberegn_svarfrist
