from django.urls import path
from django.contrib.auth import views as auth_views
from avs.views import dashboard_view, tasks_view, incoming_view, avs_view, av_view, av_save, av_create, av_search, avs_upload, suppliers_view, supplier_view, supplier_save, supplier_delete, supplier_create, machines_view, machine_view, machine_save, machine_create, machine_delete, drives_view, drive_view, drive_save, drive_create, drive_delete, av_assign, av_prio, incoming_procedure_view, incoming_procedure_save, archivist_view, archivist_save, archivists_view, archivist_create, archivist_delete, upload_view, export_csv, export_xls, export_machines, import_machines, export_drives, import_drives, overblik, genberegn_svarfrist

urlpatterns = [
    path('', tasks_view, name='tasks_view'),
    path('logind/', auth_views.LoginView.as_view(template_name='avs/login.html'), name='login_view'),
    path('logud/', auth_views.LogoutView.as_view(template_name='avs/logout.html'), name='logout_view'),
    path('upload/', upload_view, name='upload_view'),
    path('genberegn_svarfrist/', genberegn_svarfrist, name='genberegn_svarfrist'),
    path('opgaver/', dashboard_view, name='dashboard_view'),
    path('overblik/', overblik, name='overblik'),
    path('modtagelse/', incoming_view, name='incoming_view'),
    path('modtagelse_procedure/<str:a>/<str:v>/', incoming_procedure_view, name='incoming_procedure_view'),
    path('incoming_procedure_save/', incoming_procedure_save, name='incoming_procedure_save'),
    path('arkiveringsversioner/', avs_view, name='avs_view'),
    path('arkiveringsversioner/<int:nulstil>/', avs_view, name='avs_view'),
    path('av_save/', av_save, name='av_save'),
    path('av_create/', av_create, name='av_create'),
    path('av_search/', av_search, name='av_search'),
    path('av_assign/<str:avid>/<str:version>/', av_assign, name='av_assign'),
    path('av_prio/<str:avid>/<str:version>/<str:direction>', av_prio, name='av_prio'),
    path('avs_upload/', avs_upload, name='avs_upload'),
    path('leverandorer/', suppliers_view, name='suppliers_view'),
    path('leverandor/<str:lev>/', supplier_view, name='supplier_view'),
    path('supplier_save/', supplier_save, name='supplier_save'),
    path('supplier_delete/<str:pk>/', supplier_delete, name='supplier_delete'),
    path('supplier_create/', supplier_create, name='supplier_create'),

    path('export_csv/', export_csv, name='export_csv'),
    path('export_xls/', export_xls, name='export_xls'),
    path('export_machines/', export_machines, name='export_machines'),
    path('import_machines/', import_machines, name='import_machines'),
    path('export_drives/', export_drives, name='export_drives'),
    path('import_drives/', import_drives, name='import_drives'),

    path('arkivarer/', archivists_view, name='archivists_view'),
    path('arkivar/<str:ark>/', archivist_view, name='archivist_view'),
    path('archivist_save/', archivist_save, name='archivist_save'),
    path('archivist_create/', archivist_create, name='archivist_create'),
    path('archivist_delete/<str:pk>/', archivist_delete, name='archivist_delete'),

    path('maskiner/', machines_view, name='machines_view'),
    path('maskine/<str:lev>/', machine_view, name='machine_view'),
    path('machine_save/', machine_save, name='machine_save'),
    path('machine_delete/<str:pk>/', machine_delete, name='machine_delete'),
    path('machine_create/', machine_create, name='machine_create'),
    path('medier/', drives_view, name='drives_view'),
    path('medie/<str:lev>/', drive_view, name='drive_view'),
    path('drive_save/', drive_save, name='drive_save'),
    path('drive_delete/<str:pk>/', drive_delete, name='drive_delete'),
    path('drive_create/', drive_create, name='drive_create'),
    path('<str:avid>/', av_view, name='av_view'),
    path('<str:avid>/<str:version>/', av_view, name='av_view'),
]
