# Generated by Django 3.0.5 on 2020-04-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='av',
            name='prioritering',
            field=models.IntegerField(default=0),
        ),
    ]
