# Generated by Django 3.0.5 on 2020-04-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0002_av_prioritering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modtagelse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avid', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(default='Oprettelse', max_length=255)),
                ('public', models.BooleanField(default=False)),
                ('journalnummer', models.BooleanField(default=False)),
                ('titel', models.BooleanField(default=False)),
                ('kategori', models.BooleanField(default=False)),
                ('klassifikation', models.BooleanField(default=False)),
                ('leverandor', models.BooleanField(default=False)),
                ('modtaget', models.BooleanField(default=False)),
                ('find_kodeord', models.BooleanField(default=False)),
                ('kodeord', models.BooleanField(default=False)),
                ('journaliser_kodeord', models.BooleanField(default=False)),
                ('slet_kodeord', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Modtagelser',
            },
        ),
    ]
