# Generated by Django 3.0.5 on 2020-04-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0003_modtagelse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modtagelse',
            name='slet_kodeord',
        ),
    ]
