# Generated by Django 3.0.5 on 2020-04-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0005_auto_20200428_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='modtagelse',
            name='flyt_epost',
            field=models.BooleanField(default=False),
        ),
    ]
