# Generated by Django 3.0.5 on 2020-04-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0006_modtagelse_flyt_epost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arkivar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Arkivarer',
            },
        ),
    ]
