# Generated by Django 3.0.5 on 2020-04-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0008_av_arkivar'),
    ]

    operations = [
        migrations.AddField(
            model_name='modtagelse',
            name='arkivar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modtagelse',
            name='enhed',
            field=models.BooleanField(default=False),
        ),
    ]
