# Generated by Django 3.0.5 on 2020-04-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0009_auto_20200428_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='modtagelse',
            name='kontakter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modtagelse',
            name='kvittering',
            field=models.BooleanField(default=False),
        ),
    ]
