# Generated by Django 3.0.5 on 2020-04-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0011_auto_20200428_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='av',
            name='status',
            field=models.CharField(blank=True, choices=[('Modtaget', 'Modtaget'), ('Oprettet', 'Oprettet'), ('Kvitteret', 'Kvitteret'), ('Tilgængelig', 'Tilgængelig'), ('Journaliseret', 'Journaliseret'), ('Kopieret', 'Kopieret'), ('Afvikler ADA', 'Afvikler ADA'), ('Klar til test', 'Klar til test'), ('Under test', 'Under test'), ('Godkendt af tester', 'Godkendt af tester'), ('Afvikler DE', 'Afvikler DEA'), ('Afleveret til DEA', 'Afleveret til DEA'), ('Parat til godkendelse', 'Parat til godkendelse'), ('Tilbagemeldt', 'Tilbagemeldt'), ('Godkendt', 'Godkendt')], max_length=255, null=True),
        ),
    ]
