# Generated by Django 3.0.5 on 2020-04-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0014_auto_20200428_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='modtagelse',
            name='manglende_kodeord',
            field=models.BooleanField(default=False),
        ),
    ]
