# Generated by Django 3.0.5 on 2020-04-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0016_auto_20200428_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='modtagelse',
            name='bestem_storrelse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modtagelse',
            name='find_dokument',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modtagelse',
            name='find_sortnet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modtagelse',
            name='indtast_storrelse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modtagelse',
            name='kopier_av',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modtagelse',
            name='kopieret_hylde',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modtagelse',
            name='luk_medie_op',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modtagelse',
            name='placer_kasse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modtagelse',
            name='print_kodeord',
            field=models.BooleanField(default=False),
        ),
    ]
