# Generated by Django 3.0.5 on 2020-04-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0017_auto_20200429_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='maskine',
            name='avid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maskine',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
