# Generated by Django 3.0.5 on 2020-04-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0018_auto_20200429_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='medie',
            name='ibrug',
            field=models.IntegerField(default=0),
        ),
    ]
