# Generated by Django 3.0.5 on 2020-04-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0019_medie_ibrug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maskine',
            name='avid',
        ),
        migrations.RemoveField(
            model_name='maskine',
            name='version',
        ),
    ]
