# Generated by Django 3.0.5 on 2020-04-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0020_auto_20200430_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='maskine',
            name='ibrug',
            field=models.IntegerField(default=0),
        ),
    ]
