# Generated by Django 3.0.5 on 2020-05-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0023_remove_av_medie'),
    ]

    operations = [
        migrations.AddField(
            model_name='av',
            name='medie',
            field=models.ManyToManyField(blank=True, null=True, to='avs.Medie'),
        ),
    ]
