# Generated by Django 3.0.5 on 2020-05-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0025_auto_20200504_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='av',
            name='medier',
            field=models.ManyToManyField(blank=True, to='avs.Medie'),
        ),
    ]
