# Generated by Django 3.0.7 on 2020-06-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0026_auto_20200505_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='av',
            name='dea_medier',
            field=models.ManyToManyField(blank=True, related_name='dea_medier', to='avs.Medie'),
        ),
        migrations.AlterField(
            model_name='av',
            name='medier',
            field=models.ManyToManyField(blank=True, related_name='medier', to='avs.Medie'),
        ),
    ]
