# Generated by Django 3.0.7 on 2020-06-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0027_auto_20200611_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='av',
            name='status',
            field=models.CharField(blank=True, choices=[('Modtaget', 'Modtaget'), ('Oprettet', 'Oprettet'), ('Kvitteret', 'Kvitteret'), ('Tilgængelig', 'Tilgængelig'), ('Journaliseret', 'Journaliseret'), ('Kopieret', 'Kopieret'), ('Afvikler ADA', 'Afvikler ADA'), ('Klar til test', 'Klar til test'), ('Under test', 'Under test'), ('Godkendt af tester', 'Godkendt af tester'), ('Afvikler DEA', 'Afvikler DEA'), ('Afleveret til DEA', 'Afleveret til DEA'), ('Parat til godkendelse', 'Parat til godkendelse'), ('Tilbagemeldt', 'Tilbagemeldt'), ('Afventer genaflevering', 'Afventer genaflevering'), ('Godkendt', 'Godkendt')], max_length=255, null=True),
        ),
    ]
