# Generated by Django 3.0.7 on 2020-06-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0030_auto_20200617_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='av',
            name='storrelse',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
