# Generated by Django 3.0.7 on 2020-06-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0031_auto_20200618_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='av',
            name='storrelse',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
