# Generated by Django 3.0.7 on 2020-06-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0033_auto_20200618_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medie',
            name='type',
            field=models.CharField(choices=[('Solid State Drive', 'Solid State Drive'), ('USB Stick', 'USB Stick'), ('Hard Drive 3.5', 'Hard Drive 3.5'), ('Hard Drive 2.5', 'Hard Drive 2.5'), ('Ekstern SSD USB', 'Ekstern SSD USB')], max_length=255),
        ),
    ]
