# Generated by Django 3.0.7 on 2020-07-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0034_auto_20200619_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='av',
            name='antal_arbejdsdage',
            field=models.IntegerField(default=0),
        ),
    ]
