# Generated by Django 3.0.7 on 2020-07-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0035_av_antal_arbejdsdage'),
    ]

    operations = [
        migrations.AddField(
            model_name='helligdag',
            name='corona',
            field=models.BooleanField(default=False),
        ),
    ]
