# Generated by Django 3.0.7 on 2020-08-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0037_av_antal_arbejdsdage_med_coronadage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='av',
            name='status',
            field=models.CharField(blank=True, choices=[('Modtaget', 'Modtaget'), ('Oprettet', 'Oprettet'), ('Kvitteret', 'Kvitteret'), ('Mangler kodeord', 'Mangler kodeord'), ('Tilgængelig', 'Tilgængelig'), ('Journaliseret', 'Journaliseret'), ('Kopieret', 'Kopieret'), ('Afvikler ADA', 'Afvikler ADA'), ('Klar til test', 'Klar til test'), ('Under test', 'Under test'), ('Tilbagemeldt', 'Tilbagemeldt'), ('Afventer genaflevering', 'Afventer genaflevering'), ('Forhåndsgodkendt af tester', 'Forhåndsgodkendt af tester'), ('Afvikler DEA', 'Afvikler DEA'), ('Afleveret til DEA', 'Afleveret til DEA'), ('Parat til godkendelse', 'Parat til godkendelse'), ('Godkendt', 'Godkendt')], max_length=255, null=True),
        ),
    ]
