# Generated by Django 3.0.7 on 2020-09-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0038_auto_20200810_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='av',
            name='kategori',
            field=models.CharField(blank=True, choices=[('Stat', 'Stat'), ('Kommune', 'Kommune'), ('Privat', 'Privat'), ('Klassificeret', 'Klassificeret'), ('Forskningsdata', 'Forskningsdata')], max_length=255, null=True),
        ),
    ]
