# Generated by Django 3.1.4 on 2020-12-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avs', '0039_auto_20200902_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='av',
            name='public',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
